### ISSUE TITLE
How to pin clippy version?

### ISSUE THREAD

**Issue by Akuli** [ATiltedTree/setup-rust#177]
This could be a dumb question. I'm relatively new to rust.

#### Is your feature request related to a problem? Please describe
CI started failing by itself, when I didn't develop one of my projects for a while, because newer clippy has more warnings. Here's config:

```yaml
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: clippy
    - run: cargo clippy -- -D warnings
```

#### Describe the solution you'd like
A way to install a specific version of `clippy`.

#### Describe alternatives you've considered
Stopped using clippy for now, don't want project break itself
